### ISSUE TITLE
[TODO] Update outdated packages

### ISSUE THREAD

**Issue by gbowne1** [gbowne1/SPMS_ERP_MRPUpdatedRepo#16]
Outdated packages in /src/client:

| Package                           | Current | Wanted | Latest |
|-----------------------------------|---------|--------|--------|
| @babel/core | 7.16.7  | 7.17.5 | 7.17.5 |
| @fortawesome/fontawesome-svg-core | 1.2.36  | 1.3.0  | 1.3.0  |
| @fortawesome/free-solid-svg-icons | 5.15.4  | 5.15.4 | 6.0.0 |
| @fortawesome/react-fontawesome | 0.1.16 | 0.1.17 | 0.1.17 |
| @testing-library/jest-dom | 5.16.1 | 5.16.2 | 5.16.2 |
| @testing-library/react | 12.1.2 | 12.1.4 | 12.1.4 |
| axios | 0.21.4 | 0.21.4 | 0.26.1 |
| mui-datatables | 3.8.2 | 3.8.4 | 4.1.2 |
| react-router-dom | 5.3.0 | 5.3.0 | 6.2.2 |
| react-scripts | 4.0.3 | 4.0.3 | 5.0.0 |

Outdated packages in /src/server:

| Package                           | Current | Wanted | Latest |
|-----------------------------------|---------|--------|--------|
argon2 | 0.27.2 | 0.27.2 | 0.28.5 |
dotenv | 10.0.0 | 10.0.0 | 16.0.0 |
express | 4.17.1 | 4.17.3 | 4.17.3 |
express-validator | 6.11.1 | 6.14.0 | 6.14.0 |
helmet | 4.6.0 | 4.6.0 | 5.0.2 | 
multer | 1.4.2 | 1.4.4 | 1.4.4 |
nodemon | 2.0.4 | 2.0.15 | 2.0.15 |
pg | 8.3.0 | 8.7.3 | 8.7.3 |
sharp | 0.28.3 | 0.28.3 | 0.30.2 |

**Comment by 1pervysage0** [comment]
Do you want the latest or wanted?

**Comment by gbowne1** [comment]
@1pervysage0 Latest.  Thanks.
