### ISSUE TITLE
Client won't start

### ISSUE THREAD

**Issue by gbowne1** [gbowne1/SPMS_ERP_MRPUpdatedRepo#4]
running 'npm start' in Client > src 

$ npm start

> client@0.1.0 start
> react-scripts start

sh: 1: react-scripts: not found

possibly not installed

**Comment by Starboy-Sharma** [comment]
In the src folder, there is no npm script that's why you are getting error react-scripts not found. 
Make sure you are in the client directory where package.json exists and then try again. Hope it will work

**Comment by gbowne1** [comment]
Yes, you have to be in src/client but it won't start. There is a package lock in the src/client folder.

**Comment by Starboy-Sharma** [comment]
Yes, I am also facing the same problem there is a package mui-tables I think which has some dependency problem with version what I do remove the package-lock.json file and node_modules and move the react dependencies on the top then I try to install it works but I am facing other errors in running project.

**Comment by gbowne1** [comment]
according to npm the mui-datatables dependencies are listed here:
 https://www.npmjs.com/package/mui-datatables

There might be some other problems.

**Comment by gbowne1** [comment]
@Starboy-Sharma 

in order to start the client..cd to SPMS_ERP_MRPUpdatedRepo then cd to srcthen cd to client

then do a npm start.. should start the development server normally.

Current warning there are:

Compiled with warnings.

src/App.js
  Line 12:8:   'theme' is defined but never used              no-unused-vars
  Line 21:11:  'darkMode' is assigned a value but never used  no-unused-vars

src/components/Content.jsx
  Line 10:3:  'Box' is defined but never used                                                                                            no-unused-vars
  Line 11:3:  'List' is defined but never used                                                                                           no-unused-vars
  Line 12:3:  'ListItem' is defined but never used                                                                                       no-unused-vars
  Line 13:3:  'ListItemText' is defined but never used                                                                                   no-unused-vars
  Line 14:3:  'ListItemSecondaryAction' is defined but never used                                                                        no-unused-vars
  Line 95:6:  React Hook useEffect has missing dependencies: 'newTab' and 'newTab2'. Either include them or remove the dependency array  react-hooks/exhaustive-deps

src/components/DarkMode.jsx
  Line 12:6:  React Hook useEffect has a missing dependency: 'onChange'. Either include it or remove the dependency array. If 'onChange' changes too often, find the parent component that defines it and wrap that definition in useCallback  react-hooks/exhaustive-deps

src/components/EmployeeDetail.jsx
  Line 3:8:    'spmsAPI' is defined but never used                                                                    no-unused-vars
  Line 7:8:    'Typography' is defined but never used                                                                 no-unused-vars
  Line 12:10:  'Hidden' is defined but never used                                                                     no-unused-vars
  Line 12:18:  'Snackbar' is defined but never used                                                                   no-unused-vars
  Line 13:10:  'AppContext' is defined but never used                                                                 no-unused-vars
  Line 15:7:   'validationSchema' is assigned a value but never used                                                  no-unused-vars
  Line 57:6:   React Hook useEffect has a missing dependency: 'id'. Either include it or remove the dependency array  react-hooks/exhaustive-deps

src/components/EmployeeList.jsx
  Line 3:8:   'spmsAPI' is defined but never used                     no-unused-vars
  Line 53:9:  'onRowClickHandler' is assigned a value but never used  no-unused-vars

src/components/SideBar.jsx
  Line 4:10:    'library' is defined but never used               no-unused-vars
  Line 11:8:    'List' is defined but never used                  no-unused-vars
  Line 14:8:    'ListItem' is defined but never used              no-unused-vars
  Line 15:10:   'ListSubheader' is defined but never used         no-unused-vars
  Line 22:8:    'DarkMode' is defined but never used              no-unused-vars
  Line 125:9:   'theme' is assigned a value but never used        no-unused-vars
  Line 167:11:  'setDarkMode' is assigned a value but never used  no-unused-vars

src/components/SignIn.jsx
  Line 15:18:  'Snackbar' is defined but never used  no-unused-vars

src/services/auth.service.js
  Line 39:1:  Assign object to a variable before exporting as module default  import/no-anonymous-default-export

Search for the keywords to learn more about each warning.
To ignore, add // eslint-disable-next-line to the line before.

**Comment by gbowne1** [comment]
running 'npm outdated' while inside the src/client folder shows these dependencies are outdated:

$ npm outdated
Package            Current  Wanted  Latest         Location                           Depended by
argon2                  0.27.2  0.27.2  0.28.3  node_modules/argon2             server
dotenv                  10.0.0  10.0.0  14.3.2  node_modules/dotenv             server
express                 4.17.1  4.17.2  4.17.2  node_modules/express            server
express-validator   6.11.1  6.14.0  6.14.0  node_modules/express-validator  server
helmet                   4.6.0   4.6.0   5.0.2  node_modules/helmet             server
multer                    1.4.2   1.4.4   1.4.4  node_modules/multer             server
nodemon               2.0.4  2.0.15  2.0.15  node_modules/nodemon            server
pg                          8.3.0   8.7.1   8.7.1  node_modules/pg                 server
sharp                    0.28.3  0.28.3  0.29.3  node_modules/sharp              server

**Comment by gbowne1** [comment]
running 'npm outdated' while inside the src/client folder shows these dependencies are outdated:

$ npm outdated
Package           Current   Wanted   Latest  Location                       Depended by
@babel/core        7.16.7  7.16.12  7.16.12  node_modules/@babel/core       client
axios              0.21.4   0.21.4   0.25.0  node_modules/axios             client
mui-datatables      3.8.2    3.8.2    4.0.0  node_modules/mui-datatables    client
react-router-dom    5.3.0    5.3.0    6.2.1  node_modules/react-router-dom  client
react-scripts       4.0.3    4.0.3    5.0.0  node_modules/react-scripts     client

**Comment by gbowne1** [comment]
These packages were updated recently and most of these issues were fixed with recent commit/push as of  3/28/2022
