### ISSUE TITLE
[TODO] Add .github

### ISSUE THREAD

**Issue by gbowne1** [gbowne1/SPMS_ERP_MRPUpdatedRepo#8]
[TODO] Add .github folder.
 
  - Workflows
  - Pull Request Template
  - Issue Templates
  
  Use .yml instead of .md

  Add config.yml

**Comment by gbowne1** [comment]
I don't know much about the Github Actions/Workflows for REACT applications.  The ones I have seen are for deployment.

**Comment by Dun-sin** [comment]
can i work on the issue and pull request templates?

**Comment by gbowne1** [comment]
Yes you can work on this issue. @Dun-sin
